export const Ingredients = [
  "7-up",
  "absinthe",
  "agave",
  "apple",
  "apple cider",
  "apple juice",
  "apricot nectar",
  "apricot",
  "avocado",
  "banana",
  "banana nectar",
  "beer",
  "black currants",
  "blackberries",
  "blackberry juice",
  "blood orange",
  "blueberries",
  "bourbon",
  "boysenberries",
  "brandy",
  "brown sugar",
  "butterscotch",
  "cactus",
  "cactus pear",
  "cane syrup",
  "cantaloupe",
  "cantaloupe nectar",
  "caramel",
  "caramel sauce",
  "carbonated water",
  "celery",
  "chartreuse",
  "cherries",
  "cherry coke",
  "chocolate syrup",
  "cider",
  "cinnamon",
  "cinnamon stick",
  "coca cola",
  "coconut",
  "coconut rum",
  "coconut milk",
  "coffee",
  "cognac",
  "condensed milk",
  "corn syrup",
  "cranberries",
  "cranberry juice",
  "cream",
  "cucumber",
  "dates",
  "demerara sugar",
  "dr. pepper",
  "evaporated milk",
  "everclear",
  "fanta",
  "fennel seeds",
  "fig",
  "fruit nectar",
  "fudge",
  "garlic sauce",
  "gin",
  "ginger ale",
  "ginger beer",
  "ginger",
  "grape juice",
  "grapefruit juice",
  "grapes",
  "guava juice",
  "guava nectar",
  "honey",
  "honeydew melon",
  "horchata",
  "huckleberries",
  "ice cream",
  "iced coffee",
  "iced tea",
  "irish cream",
  "jalapeno",
  "kiwi",
  "kumquat",
  "lemon",
  "lemon soda",
  "lemonade",
  "lime",
  "lime juice",
  "lychee",
  "mandarin",
  "mango",
  "mango nectar",
  "maple syrup",
  "maraschino cherry",
  "mead",
  "milk",
  "mint",
  "mocha coffee",
  "molasses",
  "mountain dew",
  "nectarine",
  "nutmeg",
  "olive",
  "onion",
  "orange",
  "orange crush",
  "orange peel",
  "orange rum",
  "papaya",
  "papaya nectar",
  "passion fruit juice",
  "peach",
  "peach nectar",
  "pear",
  "pear nectar",
  "pepper",
  "pepsi cola",
  "persimmon",
  "pineapple",
  "pineapple juice",
  "plums",
  "pomegranate",
  "pomegranate juice",
  "port wine",
  "raisins",
  "raspberry",
  "raspberry jam",
  "red wine",
  "rhubarb",
  "root beer",
  "rosa",
  "rosemary",
  "rum",
  "sake",
  "salt",
  "scotch",
  "sea salt",
  "sierra mist",
  "syrup",
  "soju",
  "sour mix",
  "sparkling wine",
  "sprite",
  "squirt",
  "star anise",
  "star fruit",
  "strawberries",
  "strawberry juice",
  "sugar cane",
  "sugar cube",
  "sunkist soda",
  "sweet potato",
  "tangerine",
  "tequila",
  "tomato",
  "tomato juice",
  "tropicana",
  "vanilla syrup",
  "vanilla coke",
  "vermouth",
  "vodka",
  "water",
  "watermelon",
  "watermelon juice",
  "watermelon chnapps",
  "whiskey",
  "white sugar",
  "white wine",
  "wine",
];
